github:
  - azz
  - JounQin
  - 1stG
  - rx-ts
  - un-ts
patreon: 1stG
open_collective: pretty-quick
custom:
  - https://opencollective.com/prettier-eslint
  - https://opencollective.com/1stG
  - https://opencollective.com/rxts
  - https://opencollective.com/unrs
  - https://opencollective.com/unts
  - https://afdian.com/a/JounQin
