github:
  - azz
  - JounQin
  - 1stG
  - rx-ts
  - un-ts
patreon: 1stG
open_collective: unts
custom:
  - https://opencollective.com/1stG
  - https://opencollective.com/rxts
  - https://afdian.net/@JounQin
