name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 24
        os:
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
